<?php
// Manifiesto de posts - Generado automáticamente por generate_manifest.php
// Última actualización: 2025-11-18 09:21:52
// No editar manualmente

$posts = array (
  'aguilas-vencen-a-bravos-4-3-en-maracaibo-eybersson-polanco-se-lleva-la-victoria' => 
  array (
    'title' => 'Águilas vencen a Bravos 4-3 en Maracaibo: Eybersson Polanco se lleva la victoria',
    'subtitle' => 'Águilas se consolidan como líderes en la LVBP tras una victoria ajustada sobre Bravos, con Polanco brillando en el relevo.',
    'category' => 'Venezuela',
    'tags' => 
    array (
      0 => 'Águilas del Zulia',
      1 => 'Bravos de Margarita',
      2 => 'Eybersson Polanco',
      3 => 'Carlos Navas',
      4 => 'LVBP',
      5 => 'Beisbol',
      6 => 'Zulia',
      7 => 'Maracaibo',
      8 => 'Tiburones de La Guaira',
      9 => 'Caribes de Anzoátegui',
      10 => 'BeisbolPlay',
      11 => 'Televe',
    ),
    'date' => '17 de noviembre de 2025',
    'author' => 'Redacción Meridiano',
    'image' => 'https://www.meridiano.com//assets/img/assets/img/post-bg.jpg',
    'url' => 'https://www.meridiano.com//post/aguilas-vencen-a-bravos-4-3-en-maracaibo-eybersson-polanco-se-lleva-la-victoria.php',
  ),
  'andres-chaparro-estreno-bate-poder-aguilas-blindar-cima' => 
  array (
    'title' => 'Andrés Chaparro adelanta su estreno: el bate de poder que Águilas necesitaba para blindar la cima',
    'subtitle' => 'El Novato del Año 2023–24 se incorpora sin restricciones a Águilas del Zulia como bate de poder en 1B/3B justo antes de la Semana de La Chinita para reforzar la cima.',
    'category' => 'Venezuela',
    'tags' => 
    array (
      0 => 'Andrés Chaparro',
      1 => 'Semana de La Chinita',
      2 => 'La Chinita',
      3 => 'Novato del Año 2023–24',
      4 => 'Maracaibo',
    ),
    'date' => '17 de noviembre de 2025',
    'author' => 'Redacción Meridiano',
    'image' => 'https://www.meridiano.com//assets/img/post-bg.jpg',
    'url' => 'https://www.meridiano.com//post/andres-chaparro-estreno-bate-poder-aguilas-blindar-cima.php',
  ),
  'andretty-cordero-importado-yadier-pidio-respondio-tablazo' => 
  array (
    'title' => 'Andretty Cordero, el importado que Yadier pidió… y que respondió con un tablazo',
    'subtitle' => 'El dominicano respondió al pedido de Yadier Molina con jonrón en su primer turno y se perfila como bate de impacto en el medio del orden de Magallanes.',
    'category' => 'Venezuela',
    'tags' => 
    array (
      0 => 'Andretty Cordero',
      1 => 'Yadier Molina',
      2 => 'Yasiel Puig',
      3 => 'Sardiñas',
      4 => 'Suisbel',
      5 => 'Alfonzo Jr.',
      6 => 'Valencia',
    ),
    'date' => '14 de noviembre de 2025',
    'author' => 'Redacción Meridiano',
    'image' => 'https://www.meridiano.com//assets/img/post-bg.jpg',
    'url' => 'https://www.meridiano.com//post/andretty-cordero-importado-yadier-pidio-respondio-tablazo.php',
  ),
  'balbino-fuenmayor-semana-poder-reescribe-pulso-ofensivo-lvbp' => 
  array (
    'title' => 'Balbino Fuenmayor: una semana de poder que reescribe el pulso ofensivo de la LVBP',
    'subtitle' => 'El cañonero de Caribes gana por segunda vez el Jugador de la Semana 5 con una línea .471/.500/1.118 que impulsa la racha oriental y reconfigura la pelea ofensiva de la LVBP.',
    'category' => 'Venezuela',
    'tags' => 
    array (
      0 => 'Balbino Fuenmayor',
      1 => 'Bryan Mata',
      2 => 'Luis Peña',
      3 => 'Jugador de la Semana 5',
    ),
    'date' => '17 de noviembre de 2025',
    'author' => 'Redacción Meridiano',
    'image' => 'https://www.meridiano.com//assets/img/assets/img/post-bg.jpg',
    'url' => 'https://www.meridiano.com//post/balbino-fuenmayor-semana-poder-reescribe-pulso-ofensivo-lvbp.php',
  ),
  'castillo-y-muzziotti-el-par-de-encendidos-que-trepo-a-las-aguilas-hasta-la-azotea' => 
  array (
    'title' => 'Castillo y Muzziotti, el par de encendidos que trepó a las Águilas hasta la azotea',
    'subtitle' => 'El 1–2 de Castillo y Muzziotti puso ritmo de enero en el Zulia y trepó a las Águilas hasta la cima, con contacto, tráfico en bases y bullpen oportuno.',
    'category' => 'Venezuela',
    'tags' => 
    array (
      0 => 'Alí Castillo',
      1 => 'Simón Muzziotti',
      2 => 'Semana de La Chinita',
      3 => 'Clásico de La Chinita',
      4 => 'Juega En Línea',
      5 => 'Líder en deportes',
      6 => 'El Emergente',
      7 => 'El Universal',
    ),
    'date' => '14 de noviembre de 2025',
    'author' => 'Redacción Meridiano',
    'image' => 'https://www.meridiano.com//assets/img/post-bg.jpg',
    'url' => 'https://www.meridiano.com//post/castillo-y-muzziotti-el-par-de-encendidos-que-trepo-a-las-aguilas-hasta-la-azotea.php',
  ),
  'chinita-2025-aguilas-bravos-punta-maracaibo' => 
  array (
    'title' => 'La Chinita 2025: Águilas y Bravos se juegan algo más que la punta en Maracaibo',
    'subtitle' => 'El Juego de la Chinita cruza tradición y tabla: Águilas defienden casa y liderato ante unos Bravos que llegan en modo contendiente al Luis Aparicio.',
    'category' => 'Venezuela',
    'tags' => 
    array (
      0 => 'Juego de la Chinita',
      1 => 'Luis Aparicio "El Grande"',
      2 => 'Zulia',
      3 => 'Bravos',
      4 => 'Águilas',
      5 => 'Tiburones de La Guaira',
      6 => 'Caribes de Anzoátegui',
      7 => 'Magallanes',
      8 => 'Yasiel Puig',
      9 => 'Yadier Molina',
      10 => 'Henry Blanco',
      11 => 'Wilson García',
      12 => 'Ángel Rondón',
      13 => 'Jecksson Flores',
      14 => 'Luisangel Acuña',
      15 => 'Silvino Bracho',
      16 => 'Hernán Pérez',
      17 => 'Balbino Fuenmayor',
      18 => 'BeisbolPlay',
      19 => 'Televen',
      20 => '1 Baseball',
      21 => 'bateo situacional',
      22 => 'bullpen',
      23 => 'pitcheo',
    ),
    'date' => '18 de noviembre de 2025',
    'author' => 'Redacción Meridiano',
    'image' => 'https://www.meridiano.com//assets/img/assets/img/post-bg.jpg',
    'url' => 'https://www.meridiano.com//post/chinita-2025-aguilas-bravos-punta-maracaibo.php',
  ),
  'cinco-equipos-1-5-juegos-cima-respiracion-asistida' => 
  array (
    'title' => 'Cinco equipos en 1.5 juegos: la cima con respiración asistida',
    'subtitle' => 'Águilas, Bravos, Caribes, Tigres y Leones amanecen en 1.5 juegos, con una cima que cambia de dueño según quién use mejor la palanca y los cruces directos.',
    'category' => 'Venezuela',
    'tags' => 
    array (
      0 => 'LVBP',
      1 => 'Águilas del Zulia',
      2 => 'Bravos de Margarita',
      3 => 'Caribes de Anzoátegui',
      4 => 'Tigres de Aragua',
      5 => 'Leones del Caracas',
      6 => 'Luis Aparicio',
    ),
    'date' => '16 de noviembre de 2025',
    'author' => 'Redacción Meridiano',
    'image' => 'https://www.meridiano.com//assets/img/post-bg.jpg',
    'url' => 'https://www.meridiano.com//post/cinco-equipos-1-5-juegos-cima-respiracion-asistida.php',
  ),
  'clasicos-mueven-aguja-noche-sardinas-volteo-tablero-cima-apreto' => 
  array (
    'title' => 'Clásicos que mueven la aguja: la noche en que Sardiñas volteó el tablero y la cima se apretó',
    'subtitle' => 'Un jonrón de Luis Sardiñas en el 9.º inning volteó el Clásico Caracas–Magallanes y dejó la cima de la LVBP apretada, con Zulia respirando en la nuca.',
    'category' => 'Venezuela',
    'tags' => 
    array (
      0 => 'Henry Blanco',
      1 => 'Quijada',
      2 => 'Quintana',
      3 => 'BCV',
      4 => 'El Emergente',
      5 => 'Juega En Línea',
    ),
    'date' => '14 de noviembre de 2025',
    'author' => 'Redacción Meridiano',
    'image' => 'https://www.meridiano.com//assets/img/post-bg.jpg',
    'url' => 'https://www.meridiano.com//post/clasicos-mueven-aguja-noche-sardinas-volteo-tablero-cima-apreto.php',
  ),
  'cuarta-semana-aprieta-zulia-mete-presion-la-guaira-responde-caribes-endereza-carretera' => 
  array (
    'title' => 'La cuarta semana aprieta: Zulia mete presión, La Guaira responde y Caribes se endereza en la carretera',
    'subtitle' => 'Zulia aprieta en la cima, La Guaira responde y Caribes se endereza en una cuarta semana que ya se juega a ritmo de round robin.',
    'category' => 'LVBP',
    'tags' => 
    array (
      0 => 'Zulia',
      1 => 'La Guaira',
      2 => 'Caribes',
      3 => 'Round Robin',
    ),
    'date' => '13 de noviembre de 2025',
    'author' => 'Redacción Meridiano BB',
    'image' => 'https://www.meridiano.com//assets/img/cuarta-semana-aprieta-zulia-mete-presion-la-guaira-responde-caribes-endereza-carretera.jpg',
    'url' => 'https://www.meridiano.com//post/cuarta-semana-aprieta-zulia-mete-presion-la-guaira-responde-caribes-endereza-carretera.php',
  ),
  'festival-batazos-puerto-la-cruz-tiburones-victoria-historica-caribes' => 
  array (
    'title' => 'Festival de batazos en Puerto La Cruz: Tiburones se lleva la victoria 18-15 en un juego histórico contra Caribes',
    'subtitle' => 'Una noche histórica llena de jonrones y emoción, con un juego de 33 carreras que se convertirá en uno de los más recordados de la temporada.',
    'category' => 'Venezuela',
    'tags' => 
    array (
      0 => 'Tiburones de La Guaira',
      1 => 'Caribes de Anzoátegui',
      2 => 'Alfonso “Chico” Carrasquel',
      3 => 'Marco Davalillo',
      4 => 'Brayan Rocchio',
      5 => 'jonrones',
      6 => 'bateo',
      7 => 'bullpen',
      8 => 'Luis Peña',
      9 => 'Jadher Areinamo',
      10 => 'Franklin Barreto',
      11 => 'Herlis Rodríguez',
      12 => 'Carlos Pérez',
      13 => 'Daniel Montaño',
      14 => 'Balbino Fuenmayor',
      15 => 'Antonio Piñero',
      16 => 'Rafael Marchán',
      17 => 'BeisbolPlay',
      18 => 'Televen',
      19 => '1 Baseball',
    ),
    'date' => '17 de noviembre de 2025',
    'author' => 'Redacción Meridiano',
    'image' => 'https://www.meridiano.com//assets/img/assets/img/post-bg.jpg',
    'url' => 'https://www.meridiano.com//post/festival-batazos-puerto-la-cruz-tiburones-victoria-historica-caribes.php',
  ),
  'gabriel-arias-pausa-guaira-reconfigura-libreto-diciembre' => 
  array (
    'title' => 'Gabriel Arias hace una pausa: La Guaira reconfigura su libreto a la espera de diciembre',
    'subtitle' => 'La salida temporal de Gabriel Arias obliga a Tiburones a rearmar el infield y a virar hacia el béisbol situacional mientras espera su regreso en diciembre.',
    'category' => 'Venezuela',
    'tags' => 
    array (
      0 => 'Gabriel Arias',
      1 => 'La Guaira',
      2 => 'Estados Unidos',
    ),
    'date' => '17 de noviembre de 2025',
    'author' => 'Redacción Meridiano',
    'image' => 'https://www.meridiano.com//assets/img/assets/img/post-bg.jpg',
    'url' => 'https://www.meridiano.com//post/gabriel-arias-pausa-guaira-reconfigura-libreto-diciembre.php',
  ),
  'gleyber-torres-leones' => 
  array (
    'title' => 'Gleyber Torres, la pieza que puede subirle un piso más al lineup de Leones',
    'subtitle' => 'El grandeliga que puede transformar el lineup y la ecuación competitiva de Leones en la LVBP 2025–26',
    'category' => 'LVBP',
    'tags' => 
    array (
      0 => 'Leones del Caracas',
      1 => 'Gleyber Torres',
      2 => 'Ofensiva',
      3 => 'Grandes Ligas',
    ),
    'date' => '12 de noviembre de 2025',
    'author' => 'Redacción Meridiano',
    'image' => 'https://www.meridiano.com//assets/img/gleyber-torres-leones.webp',
    'url' => 'https://www.meridiano.com//post/gleyber-torres-leones.php',
  ),
  'henry-blanco-dos-juegos-al-dique-como-se-administra-un-clubhouse-sin-su-piloto' => 
  array (
    'title' => 'Henry Blanco, dos juegos al dique: cómo se administra un clubhouse sin su piloto',
    'subtitle' => 'La suspensión de dos juegos y multa a Henry Blanco llega en una semana de tabla comprimida y obliga a Bravos a administrar bullpen y clubhouse sin su piloto.',
    'category' => 'Venezuela',
    'tags' => 
    array (
      0 => 'Henry Blanco',
      1 => 'Quijada',
      2 => 'Quintana',
      3 => 'BCV',
    ),
    'date' => '14 de noviembre de 2025',
    'author' => 'Redacción Meridiano',
    'image' => 'https://www.meridiano.com//assets/img/post-bg.jpg',
    'url' => 'https://www.meridiano.com//post/henry-blanco-dos-juegos-al-dique-como-se-administra-un-clubhouse-sin-su-piloto.php',
  ),
  'henry-blanco-suspendido-dos-juegos-temple-lider-pelea-punta' => 
  array (
    'title' => 'Henry Blanco suspendido: dos juegos para probar el temple de un líder que pelea la punta',
    'subtitle' => 'La LVBP castiga con dos juegos a Henry Blanco y Bravos debe responder sin su mánager en plena pelea por la cima de una tabla apretada.',
    'category' => 'Venezuela',
    'tags' => 
    array (
      0 => 'Henry Blanco',
      1 => 'Maracaibo',
      2 => 'Monumental',
      3 => 'Margarita',
    ),
    'date' => '16 de noviembre de 2025',
    'author' => 'Redacción Meridiano',
    'image' => 'https://www.meridiano.com//assets/img/post-bg.jpg',
    'url' => 'https://www.meridiano.com//post/henry-blanco-suspendido-dos-juegos-temple-lider-pelea-punta.php',
  ),
  'jadher-areinamo-novato-volante-lineup-ranking-conversacion-grande' => 
  array (
    'title' => 'Jadher Areinamo, un novato al volante del lineup: del “ranking” a la conversación grande',
    'subtitle' => 'El sub-23 de Tiburones se trepa al #1 del Ranking Líder con poder metódico y volumen útil que lo mete de lleno en la conversación grande de la LVBP.',
    'category' => 'Venezuela',
    'tags' => 
    array (
      0 => 'Jadher Areinamo',
      1 => 'Líder de Bateo',
    ),
    'date' => '16 de noviembre de 2025',
    'author' => 'Redacción Meridiano',
    'image' => 'https://www.meridiano.com//assets/img/post-bg.webp',
    'url' => 'https://www.meridiano.com//post/jadher-areinamo-novato-volante-lineup-ranking-conversacion-grande.php',
  ),
  'luis-pena-dominicano-ponches-plan-gobierno-guaira' => 
  array (
    'title' => 'Luis Peña, el dominicano que convirtió los ponches en plan de gobierno en La Guaira',
    'subtitle' => 'El dominicano domina la LVBP en ponches e innings lanzados con una receta de primer strike obligatorio y mecánica compacta que equilibra el poder de Tiburones.',
    'category' => 'Venezuela',
    'tags' => 
    array (
      0 => 'Luis Peña',
      1 => 'La Guaira',
    ),
    'date' => '15 de noviembre de 2025',
    'author' => 'Redacción Meridiano',
    'image' => 'https://www.meridiano.com//assets/img/post-bg.jpg',
    'url' => 'https://www.meridiano.com//post/luis-pena-dominicano-ponches-plan-gobierno-guaira.php',
  ),
  'lvbp-encoge-aguilas-mando-cuatro-equipos-1-5-juegos' => 
  array (
    'title' => 'La LVBP se encoge: Águilas al mando y cuatro equipos a 1.5 juegos',
    'subtitle' => 'La clasificación del 14/11 dejó a Águilas en la cima y cuatro equipos a solo 1.5 juegos, en una LVBP donde cada serie pesa como juego de seis puntos.',
    'category' => 'Venezuela',
    'tags' => 
    array (
      0 => 'Venezuela',
      1 => 'LVBP',
      2 => 'Águilas del Zulia',
      3 => 'Tigres de Aragua',
      4 => 'Bravos de Margarita',
      5 => 'Caribes de Anzoátegui',
      6 => 'Leones del Caracas',
      7 => 'Tiburones de La Guaira',
      8 => 'Cardenales de Lara',
      9 => 'Navegantes del Magallanes',
    ),
    'date' => '15 de noviembre de 2025',
    'author' => 'Redacción Meridiano',
    'image' => 'https://www.meridiano.com//assets/img/post-bg.jpg',
    'url' => 'https://www.meridiano.com//post/lvbp-encoge-aguilas-mando-cuatro-equipos-1-5-juegos.php',
  ),
  'lvbp-madrugada-molina-wilson-balbino-500' => 
  array (
    'title' => 'Una LVBP en modo madrugada: Molina aterriza ganando, Wilson firma una noche para el recuerdo y Balbino alcanza los 500',
    'subtitle' => 'En dos noches de pelota venezolana, Molina vuelve ganando con Magallanes, Wilson García conecta tres jonrones y Balbino Fuenmayor rompe la barrera de los 500 hits.',
    'category' => 'Venezuela',
    'tags' => 
    array (
      0 => 'Yadier Molina',
      1 => 'Yasiel Puig',
      2 => 'Wilson García',
      3 => 'Balbino Fuenmayor',
      4 => 'Eduardo Pérez',
      5 => 'Amílcar Chirinos',
      6 => 'Edwar Colina',
      7 => 'Felipe Vázquez',
      8 => 'Valencia',
      9 => 'Barquisimeto',
      10 => 'Puerto La Cruz',
      11 => '500 hits en la LVBP',
    ),
    'date' => '15 de noviembre de 2025',
    'author' => 'Redacción Meridiano',
    'image' => 'https://www.meridiano.com//assets/img/post-bg.jpg',
    'url' => 'https://www.meridiano.com//post/lvbp-madrugada-molina-wilson-balbino-500.php',
  ),
  'magallanes-mueve-el-tablero' => 
  array (
    'title' => 'Magallanes mueve el tablero: el debut de Puig, la baja de Rodríguez y un plan de bateo con urgencia de puntos',
    'subtitle' => 'El debut de Yasiel Puig, la baja de Rodríguez y los ajustes de bateo que marcan la semana en la nave turca.',
    'category' => 'LVBP',
    'tags' => 
    array (
      0 => 'Magallanes',
      1 => 'Yasiel Puig',
      2 => 'Ofensiva',
      3 => 'Carlos Rodríguez',
    ),
    'date' => '13 de noviembre de 2025',
    'author' => 'Redacción Meridiano',
    'image' => 'https://www.meridiano.com//assets/img/puig-magallanes.jpg',
    'url' => 'https://www.meridiano.com//post/magallanes-mueve-el-tablero.php',
  ),
  'maximo-acosta-motor-acelera-tiburones-fecha-salida' => 
  array (
    'title' => 'Máximo Acosta, el motor que acelera a Tiburones… y que ya pone fecha de salida',
    'subtitle' => 'El campocorto de Tiburones de La Guaira vive una última semana de alto impacto en la LVBP antes de adelantar su salida por motivos familiares y de visa.',
    'category' => 'Venezuela',
    'tags' => 
    array (
      0 => 'Máximo Acosta',
      1 => 'Macuto',
      2 => 'LVBP',
      3 => 'Tiburones de La Guaira',
    ),
    'date' => '13 de noviembre de 2025',
    'author' => 'Redacción Meridiano',
    'image' => 'https://www.meridiano.com//assets/img/post-bg.jpg',
    'url' => 'https://www.meridiano.com//post/maximo-acosta-motor-acelera-tiburones-fecha-salida.php',
  ),
  'molina-endereza-brujula-efecto-puig-magallanes' => 
  array (
    'title' => 'Molina endereza la brújula: química en el clubhouse y el efecto Puig reencaminan a Magallanes',
    'subtitle' => 'Con Yadier Molina ordenando roles y Yasiel Puig aportando disciplina y protección al medio del orden, Magallanes pasa de remar contra corriente a jugar con método.',
    'category' => 'Venezuela',
    'tags' => 
    array (
      0 => 'Yadier Molina',
      1 => 'Yasiel Puig',
      2 => 'Núñez',
    ),
    'date' => '17 de noviembre de 2025',
    'author' => 'Redacción Meridiano',
    'image' => 'https://www.meridiano.com//assets/img/assets/img/post-bg.jpg',
    'url' => 'https://www.meridiano.com//post/molina-endereza-brujula-efecto-puig-magallanes.php',
  ),
  'noche-apreto-campeonato-bravos-asalta-cima-caribes-repite-nave-respira-lara-baja-volumen-caracas' => 
  array (
    'title' => 'La noche que apretó el campeonato: Bravos asalta la cima, Caribes repite, la Nave respira y Lara le baja el volumen a Caracas',
    'subtitle' => 'La jornada del 15/11 movió la tabla: Bravos iguala la cima, Caribes repite ante La Guaira, Magallanes reacciona y Lara frena al Caracas en una LVBP que ya huele a enero.',
    'category' => 'Venezuela',
    'tags' => 
    array (
      0 => 'Hernán Pérez',
      1 => 'Balbino Fuenmayor',
      2 => 'Yadier Molina',
      3 => 'Renato Núñez',
      4 => 'Yasiel Puig',
      5 => 'Adrián Almeida',
      6 => 'Maracaibo',
      7 => 'Puerto La Cruz',
      8 => 'Barquisimeto',
      9 => 'Estadio Luis Aparicio',
    ),
    'date' => '16 de noviembre de 2025',
    'author' => 'Redacción Meridiano',
    'image' => 'https://www.meridiano.com//assets/img/post-bg.jpg',
    'url' => 'https://www.meridiano.com//post/noche-apreto-campeonato-bravos-asalta-cima-caribes-repite-nave-respira-lara-baja-volumen-caracas.php',
  ),
  'noche-barajo-cima-zulia-nave-caribes-aragua' => 
  array (
    'title' => 'La noche que barajó la cima: Zulia se despega, la Nave acelera, Caribes aprieta y Aragua se mira al espejo',
    'subtitle' => 'Águilas toma el liderato en solitario, Magallanes firma una semana 5–1, Caribes golpea de nuevo a La Guaira y Tigres se enreda con RISP en una LVBP que ya juega a modo enero.',
    'category' => 'Venezuela',
    'tags' => 
    array (
      0 => 'Yadier Molina',
      1 => 'Hernán Pérez',
      2 => 'Ángelo Castellano',
      3 => 'Eduardo Torrealba',
      4 => 'Silvino Bracho',
      5 => 'Renato Núñez',
      6 => 'Luis Sardiñas',
      7 => 'Rafael Marchán',
      8 => 'La Chinita',
      9 => 'Maracaibo',
      10 => 'Valencia',
      11 => 'Puerto La Cruz',
      12 => 'Maracay',
    ),
    'date' => '17 de noviembre de 2025',
    'author' => 'Redacción Meridiano',
    'image' => 'https://www.meridiano.com//assets/img/post-bg.jpg',
    'url' => 'https://www.meridiano.com//post/noche-barajo-cima-zulia-nave-caribes-aragua.php',
  ),
  'rocio-despues-temblor-efecto-domino-cese-guaira' => 
  array (
    'title' => 'Rocío después del temblor: el efecto dominó del cese en La Guaira',
    'subtitle' => 'El despido de Gregorio Petit y la reacción pública de Brayan Rocchio desatan un temblor en Tiburones y obligan a La Guaira a blindar método y proyecto en plena pelea por la tabla.',
    'category' => 'Venezuela',
    'tags' => 
    array (
      0 => 'Brayan Rocchio',
      1 => 'Gregorio Petit',
      2 => 'MLB',
    ),
    'date' => '17 de noviembre de 2025',
    'author' => 'Redacción Meridiano',
    'image' => 'https://www.meridiano.com//assets/img/assets/img/post-bg.jpg',
    'url' => 'https://www.meridiano.com//post/rocio-despues-temblor-efecto-domino-cese-guaira.php',
  ),
  'semana-5-resumen-analitico-lvbp-naufragio-turco-vuelo-zulia' => 
  array (
    'title' => 'Semana 5 — Resumen analítico: Una semana de locos en la LVBP, del naufragio turco al vuelo del Zulia.',
    'subtitle' => 'Entre el 10 y el 16 de noviembre, Águilas se adueñó de la cima, Magallanes resucitó con Molina y Puig, Caribes se convirtió en verdugo de Tiburones y Tigres encadenó seis derrotas al hilo.',
    'category' => 'Venezuela',
    'tags' => 
    array (
      0 => 'Yadier Molina',
      1 => 'Yasiel Puig',
      2 => 'Eduardo Pérez',
      3 => 'Luis Sardiñas',
      4 => 'Renato Núñez',
      5 => 'Wilson García',
      6 => 'Jecksson Flores',
      7 => 'Luisangel Acuña',
      8 => 'Ángel Rondón',
      9 => 'Henry Blanco',
      10 => 'Balbino Fuenmayor',
      11 => 'Antonio Piñero',
      12 => 'Hernán Pérez',
      13 => 'Rafael Marchán',
      14 => 'Alcides Escobar',
      15 => 'Luis Peña',
      16 => 'Adrián Almeida',
      17 => 'Héctor Giménez',
      18 => 'Jadher Areinamo',
      19 => 'Bryan Mata',
      20 => 'Felipe Vázquez',
      21 => 'Ángelo Castellano',
      22 => 'Eduardo Torrealba',
      23 => 'Silvino Bracho',
      24 => 'Valencia',
      25 => 'Maracay',
      26 => 'Maracaibo',
      27 => 'Barquisimeto',
      28 => 'Guatamare',
      29 => 'Puerto La Cruz',
      30 => 'UCV',
      31 => 'Semana de La Chinita',
      32 => 'Juego de La Chinita',
      33 => 'BeisbolPlay',
    ),
    'date' => '17 de noviembre de 2025',
    'author' => 'Redacción Meridiano',
    'image' => 'https://www.meridiano.com//assets/img/assets/img/post-bg.jpg',
    'url' => 'https://www.meridiano.com//post/semana-5-resumen-analitico-lvbp-naufragio-turco-vuelo-zulia.php',
  ),
  'silvino-bracho-cerrando-metronomo-dos-rescates-cumbre-rapaz' => 
  array (
    'title' => 'Silvino Bracho, cerrando con metrónomo: a dos rescates de la cumbre rapaz',
    'subtitle' => 'El cerrador rapaz llegó a seis salvados con un cierre de cinco pitcheos, se metió en el top-13 histórico de la LVBP y quedó a dos rescates del récord de Águilas.',
    'category' => 'Venezuela',
    'tags' => 
    array (
      0 => 'Silvino Bracho',
      1 => 'Jay "La Bala" Baller',
      2 => 'Giovanny Carrara',
      3 => 'Semana de La Chinita',
      4 => 'Maracaibo',
    ),
    'date' => '17 de noviembre de 2025',
    'author' => 'Redacción Meridiano',
    'image' => 'https://www.meridiano.com//assets/img/assets/img/post-bg.jpg',
    'url' => 'https://www.meridiano.com//post/silvino-bracho-cerrando-metronomo-dos-rescates-cumbre-rapaz.php',
  ),
  'tiburones-mueve-timon-gregorio-petit-marco-davalillo-mando' => 
  array (
    'title' => 'Tiburones mueve el timón: Gregorio Petit sale y Marco Davalillo asume el mando',
    'subtitle' => 'La Guaira cesa a Gregorio Petit, entrega el mando a Marco Davalillo y busca un viraje inmediato en resultados y método en plena tabla apretada.',
    'category' => 'Venezuela',
    'tags' => 
    array (
      0 => 'Marco Davalillo',
      1 => 'Gregorio Petit',
      2 => 'Javier Colina',
      3 => 'Brayan Rocchio',
      4 => 'MLB',
    ),
    'date' => '17 de noviembre de 2025',
    'author' => 'Redacción Meridiano',
    'image' => 'https://www.meridiano.com//assets/img/assets/img/post-bg.jpg',
    'url' => 'https://www.meridiano.com//post/tiburones-mueve-timon-gregorio-petit-marco-davalillo-mando.php',
  ),
  'tres-jonrones-21-heroes-leyenda-pendiente-hazana-casi-nadie-logra-venezuela' => 
  array (
    'title' => 'Tres jonrones, 21 héroes y una leyenda pendiente: la hazaña que casi nadie logra en Venezuela',
    'subtitle' => 'Solo 22 juegos de tres jonrones en casi ocho décadas de LVBP, coronados por la gesta de Wilson García en 2025 y el santo grial pendiente del cuarto cuadrangular.',
    'category' => 'Venezuela',
    'tags' => 
    array (
      0 => 'Wilson García',
      1 => 'Bill Taylor',
      2 => 'Stanley Jok',
      3 => 'Jim Pendleton',
      4 => 'Ken Harrelson',
      5 => 'Jacinto Hernández',
      6 => 'Bob Darwin',
      7 => 'Larry Parrish',
      8 => 'Tomás Pérez',
      9 => 'Pedro Castellano',
      10 => 'Jason Lane',
      11 => 'Robert Pérez',
      12 => 'Eliézer Alfonzo',
      13 => 'Richard Hidalgo',
      14 => 'Danny Dorn',
      15 => 'Scott Van Slyke',
      16 => 'Javier Herrera',
      17 => 'Alex Cabrera',
      18 => 'Mario Lissón',
      19 => 'Teodoro Martínez',
      20 => 'Carlos Castro',
      21 => 'Russell Rac',
      22 => 'Cleiverth Pérez',
      23 => 'Robinson Hernández',
      24 => 'Luis Aparicio "El Grande"',
      25 => 'Alejandro Borges',
      26 => 'Maracaibo',
      27 => 'Macuto',
      28 => 'Estadio Universitario',
    ),
    'date' => '15 de noviembre de 2025',
    'author' => 'Redacción Meridiano',
    'image' => 'https://www.meridiano.com//assets/img/post-bg.webp',
    'url' => 'https://www.meridiano.com//post/tres-jonrones-21-heroes-leyenda-pendiente-hazana-casi-nadie-logra-venezuela.php',
  ),
  'yadier-molina-magallanes-segunda-etapa' => 
  array (
    'title' => 'Yadier Molina y su ruta caribeña: el regreso del Capitán al Magallanes',
    'subtitle' => 'Repaso detallado de la segunda etapa de Yadier Molina con el Magallanes, sus logros en ligas del Caribe y su crecimiento como dirigente.',
    'category' => 'LVBP',
    'tags' => 
    array (
      0 => 'Magallanes',
      1 => 'Yadier Molina',
      2 => 'Dirigente',
      3 => 'Caribe',
    ),
    'date' => '8 de noviembre de 2025',
    'author' => 'Redacción Meridiano BB',
    'image' => 'https://www.meridiano.com//assets/img/yadier-molina-magallanes-segunda-etapa.jpg',
    'url' => 'https://www.meridiano.com//post/yadier-molina-magallanes-segunda-etapa.php',
  ),
  'yonathan-daza-madero-ofensiva-leones' => 
  array (
    'title' => 'Yonathan Daza, el madero que hoy explica la ofensiva de Leones',
    'subtitle' => 'El jardinero derecho de Leones del Caracas vive una semana de ensueño y se convierte en el nuevo referente ofensivo del equipo capitalino.',
    'category' => 'LVBP',
    'tags' => 
    array (
      0 => 'Leones del Caracas',
      1 => 'Yonathan Daza',
      2 => 'Ofensiva',
      3 => 'Jugador de la Semana',
    ),
    'date' => '12 de noviembre de 2025',
    'author' => 'Redacción Meridiano',
    'image' => 'https://www.meridiano.com//assets/img/yonathan-daza-madero-ofensiva-leones.webp',
    'url' => 'https://www.meridiano.com//post/yonathan-daza-madero-ofensiva-leones.php',
  ),
);
?>